#pragma once
#include "ShaderAPI.h"

#include <d3d12.h>

namespace EduEngine
{
	__forceinline const char* VarTypeStr(SHADER_VARIABLE_TYPE t)
	{
		switch (t)
		{
		case EduEngine::SHADER_VARIABLE_TYPE_STATIC: return "STATIC";
		case EduEngine::SHADER_VARIABLE_TYPE_MUTABLE: return "MUTABLE";
		case EduEngine::SHADER_VARIABLE_TYPE_DYNAMIC: return "DYNAMIC";
		case EduEngine::SHADER_VARIABLE_TYPE_NUM_TYPES: return "NUM_TYPES";
		default: return "?DEFAULT?";
		}
	};

	__forceinline const char* InputTypeStr(D3D_SHADER_INPUT_TYPE t)
	{
		switch (t)
		{
		case D3D_SIT_CBUFFER: return "CBUFFER";
		case D3D_SIT_TBUFFER: return "TBUFFER";
		case D3D_SIT_TEXTURE: return "TEXTURE";
		case D3D_SIT_SAMPLER: return "SAMPLER";
		case D3D_SIT_UAV_RWTYPED: return "UAV_RWTYPED";
		case D3D_SIT_STRUCTURED: return "STRUCTURED";
		case D3D_SIT_UAV_RWSTRUCTURED: return "UAV_RWSTRUCTURED";
		case D3D_SIT_BYTEADDRESS: return "BYTEADDRESS";
		case D3D_SIT_UAV_RWBYTEADDRESS: return "UAV_RWBYTEADDRESS";
		case D3D_SIT_UAV_APPEND_STRUCTURED: return "UAV_APPEND_STRUCTURED";
		case D3D_SIT_UAV_CONSUME_STRUCTURED: return "UAV_CONSUME_STRUCTURED";
		case D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER: return "UAV_RWSTRUCTURED_WITH_COUNTER";
		case D3D_SIT_RTACCELERATIONSTRUCTURE: return "RTACCELERATIONSTRUCTURE";
		case D3D_SIT_UAV_FEEDBACKTEXTURE: return "UAV_FEEDBACKTEXTURE";
		default: return "??DEFAULT??";
		}
	};

	__forceinline const char* SrvDimStr(D3D_SRV_DIMENSION t)
	{
		switch (t)
		{
		case D3D_SRV_DIMENSION_UNKNOWN: return "UNKNOWN";
		case D3D_SRV_DIMENSION_BUFFER: return "BUFFER";
		case D3D_SRV_DIMENSION_TEXTURE1D: return "TEXTURE1D";
		case D3D_SRV_DIMENSION_TEXTURE1DARRAY: return "TEXTURE1DARRAY";
		case D3D_SRV_DIMENSION_TEXTURE2D: return "TEXTURE2D";
		case D3D_SRV_DIMENSION_TEXTURE2DARRAY: return "TEXTURE2DARRAY";
		case D3D_SRV_DIMENSION_TEXTURE2DMS: return "TEXTURE2DMS";
		case D3D_SRV_DIMENSION_TEXTURE2DMSARRAY: return "TEXTURE2DMSARRAY";
		case D3D_SRV_DIMENSION_TEXTURE3D: return "TEXTURE3D";
		case D3D_SRV_DIMENSION_TEXTURECUBE: return "TEXTURECUBE";
		case D3D_SRV_DIMENSION_TEXTURECUBEARRAY: return "TEXTURECUBEARRAY";
		case D3D_SRV_DIMENSION_BUFFEREX: return "BUFFEREX";
		default: return "??DEFAULT??";
		}
	};

	__forceinline const char* ShaderTypeStr(EDU_SHADER_TYPE t)
	{
		switch (t)
		{
		case EduEngine::EDU_SHADER_TYPE_VERTEX: return "VERTEX";
		case EduEngine::EDU_SHADER_TYPE_GEOMETRY: return "GEOMETRY";
		case EduEngine::EDU_SHADER_TYPE_PIXEL: return "PIXEL";
		case EduEngine::EDU_SHADER_TYPE_COMPUTE: return "COMPUTE";
		default: return "??DEFAULT??";
		}
	};

	__forceinline const char* ParamTypeStr(D3D12_ROOT_PARAMETER_TYPE t)
	{
		switch (t)
		{
		case D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE: return "DESCRIPTOR_TABLE";
		case D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS: return "32BIT_CONSTANTS";
		case D3D12_ROOT_PARAMETER_TYPE_CBV: return "CBV";
		case D3D12_ROOT_PARAMETER_TYPE_SRV: return "SRV";
		case D3D12_ROOT_PARAMETER_TYPE_UAV: return "UAV";
		default: return "??Default??";
		}
	}

	__forceinline const char* SdrVisStr(D3D12_SHADER_VISIBILITY t)
	{
		switch (t)
		{
		case D3D12_SHADER_VISIBILITY_ALL: return "ALL";
		case D3D12_SHADER_VISIBILITY_VERTEX: return "VERTEX";
		case D3D12_SHADER_VISIBILITY_HULL: return "HULL";
		case D3D12_SHADER_VISIBILITY_DOMAIN: return "DOMAIN";
		case D3D12_SHADER_VISIBILITY_GEOMETRY: return "GEOMETRY";
		case D3D12_SHADER_VISIBILITY_PIXEL: return "PIXEL";
		case D3D12_SHADER_VISIBILITY_AMPLIFICATION: return "AMPLIFICATION";
		case D3D12_SHADER_VISIBILITY_MESH: return "MESH";
		default: return "??Default??";
		}
	}

	__forceinline const char* RangeTypeStr(D3D12_DESCRIPTOR_RANGE_TYPE t)
	{
		switch (t)
		{
		case D3D12_DESCRIPTOR_RANGE_TYPE_SRV: return "SRV";
		case D3D12_DESCRIPTOR_RANGE_TYPE_UAV: return "UAV";
		case D3D12_DESCRIPTOR_RANGE_TYPE_CBV: return "CBV";
		case D3D12_DESCRIPTOR_RANGE_TYPE_SAMPLER: return "SAMPLER";
		default: return "??Default??";
		}
	};

	__forceinline const char* FilterStr(D3D12_FILTER f)
	{
		switch (f)
		{
		case D3D12_FILTER_MIN_MAG_MIP_POINT: return "MIN_MAG_MIP_POINT";
		case D3D12_FILTER_MIN_MAG_POINT_MIP_LINEAR: return "MAG_POINT_MIP_LINEAR:";
		case D3D12_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT: return "MIN_POINT_MAG_LINEAR_MIP_POINT";
		case D3D12_FILTER_MIN_POINT_MAG_MIP_LINEAR: return "MIN_POINT_MAG_MIP_LINEAR";
		case D3D12_FILTER_MIN_LINEAR_MAG_MIP_POINT: return "MIN_LINEAR_MAG_MIP_POINT";
		case D3D12_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR: return "MIN_LINEAR_MAG_POINT_MIP_LINEAR";
		case D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT: return "MIN_MAG_LINEAR_MIP_POINT";
		case D3D12_FILTER_MIN_MAG_MIP_LINEAR: return "MIN_MAG_MIP_LINEAR";
		case D3D12_FILTER_ANISOTROPIC: return "ANISOTROPIC";
		case D3D12_FILTER_COMPARISON_MIN_MAG_MIP_POINT: return "COMPARISON_MIN_MAG_MIP_POINT";
		case D3D12_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR: return "COMPARISON_MIN_MAG_POINT_MIP_LINEAR";
		case D3D12_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT: return "COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT";
		case D3D12_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR: return "COMPARISON_MIN_POINT_MAG_MIP_LINEAR";
		case D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT: return "COMPARISON_MIN_LINEAR_MAG_MIP_POINT";
		case D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR: return "COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR";
		case D3D12_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT: return "COMPARISON_MIN_MAG_LINEAR_MIP_POINT";
		case D3D12_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR: return "COMPARISON_MIN_MAG_MIP_LINEAR";
		case D3D12_FILTER_COMPARISON_ANISOTROPIC: return "COMPARISON_ANISOTROPIC";
		case D3D12_FILTER_MINIMUM_MIN_MAG_MIP_POINT: return "MINIMUM_MIN_MAG_MIP_POINT";
		case D3D12_FILTER_MINIMUM_MIN_MAG_POINT_MIP_LINEAR: return "MINIMUM_MIN_MAG_POINT_MIP_LINEAR";
		case D3D12_FILTER_MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT: return "MINIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT";
		case D3D12_FILTER_MINIMUM_MIN_POINT_MAG_MIP_LINEAR: return "MINIMUM_MIN_POINT_MAG_MIP_LINEAR";
		case D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_MIP_POINT: return "MINIMUM_MIN_LINEAR_MAG_MIP_POINT";
		case D3D12_FILTER_MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR: return "MINIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR";
		case D3D12_FILTER_MINIMUM_MIN_MAG_LINEAR_MIP_POINT: return "MINIMUM_MIN_MAG_LINEAR_MIP_POINT";
		case D3D12_FILTER_MINIMUM_MIN_MAG_MIP_LINEAR: return "MINIMUM_MIN_MAG_MIP_LINEAR";
		case D3D12_FILTER_MINIMUM_ANISOTROPIC: return "MINIMUM_ANISOTROPIC";
		case D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_POINT: return "MAXIMUM_MIN_MAG_MIP_POINT";
		case D3D12_FILTER_MAXIMUM_MIN_MAG_POINT_MIP_LINEAR: return "MAXIMUM_MIN_MAG_POINT_MIP_LINEAR";
		case D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT: return "MAXIMUM_MIN_POINT_MAG_LINEAR_MIP_POINT";
		case D3D12_FILTER_MAXIMUM_MIN_POINT_MAG_MIP_LINEAR: return "MAXIMUM_MIN_POINT_MAG_MIP_LINEAR";
		case D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_MIP_POINT: return "MAXIMUM_MIN_LINEAR_MAG_MIP_POINT";
		case D3D12_FILTER_MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR: return "MAXIMUM_MIN_LINEAR_MAG_POINT_MIP_LINEAR";
		case D3D12_FILTER_MAXIMUM_MIN_MAG_LINEAR_MIP_POINT: return "MAXIMUM_MIN_MAG_LINEAR_MIP_POINT";
		case D3D12_FILTER_MAXIMUM_MIN_MAG_MIP_LINEAR: return "MAXIMUM_MIN_MAG_MIP_LINEAR";
		case D3D12_FILTER_MAXIMUM_ANISOTROPIC: return "MAXIMUM_ANISOTROPIC";
		default: return "??DEFAULT??";
		}
	};
}